# Generated by Django 5.1.5 on 2025-02-15 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocxTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shartnoma', models.FileField(upload_to='uploads/docx_org_templates')),
                ('buyruq', models.FileField(upload_to='uploads/docx_org_templates')),
                ('dalolatnoma', models.FileField(upload_to='uploads/docx_org_templates')),
                ('grafik', models.FileField(upload_to='uploads/docx_org_templates')),
                ('product_type', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'docx_template',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GeneratedDocPdfModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_by', models.IntegerField()),
                ('updated_by', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(max_length=1024)),
                ('shartnoma_docx', models.FileField(upload_to='uploads/docx')),
                ('buyruq_docx', models.FileField(upload_to='uploads/docx')),
                ('dalolatnoma_docx', models.FileField(upload_to='uploads/docx')),
                ('grafik_docx', models.FileField(upload_to='uploads/docx')),
                ('shartnoma_pdf', models.FileField(upload_to='uploads/pdf')),
                ('buyruq_pdf', models.FileField(upload_to='uploads/pdf')),
                ('dalolatnoma_pdf', models.FileField(upload_to='uploads/pdf')),
                ('grafik_pdf', models.FileField(upload_to='uploads/pdf')),
                ('qrcode', models.FileField(upload_to='uploads/qrcode')),
            ],
            options={
                'db_table': 'generated_doc_pdf',
                'managed': False,
            },
        ),
    ]
